### ISSUE TITLE
Uncaught TypeError: atom.workspace.getActiveEditor is not a function

### ISSUE THREAD

**Issue by mariusvn** [aloncarmel/devunityatom#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Unknown Windows Version
**Thrown From**: [devunity](https://github.com/aloncarmel/devunityatom) package, v2.2.0
### Stack Trace

Uncaught TypeError: atom.workspace.getActiveEditor is not a function

```
At /C:/Users/Marius/.atom/packages/devunity/lib/devunity.coffee:681

TypeError: atom.workspace.getActiveEditor is not a function
    at DevunityView.getLanguage (file:///C:/Users/Marius/.atom/packages/devunity/lib/devunity.coffee:410:29)
    at DevunityView.start (file:///C:/Users/Marius/.atom/packages/devunity/lib/devunity.coffee:288:19)
    at atom-workspace.<anonymous> (file:///C:/Users/Marius/.atom/packages/devunity/lib/devunity.coffee:217:63)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Marius\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Marius\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Marius\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Marius\AppData\Local\atom\app-1.2.0\resources\app.asar\src\atom-environment.js:984:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -6:54.1.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -5:44.7.0 core:paste (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -5:43.1.0 core:confirm (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -5:41.2.0 core:backspace (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -5:41.1.0 core:confirm (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -5:39.8.0 core:backspace (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -5:36.4.0 core:paste (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -5:34.9.0 core:confirm (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -5:33.5.0 core:backspace (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -4:44.5.0 core:paste (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -4:43.1.0 core:confirm (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -4:39.9.0 core:backspace (atom-text-editor#firepad.firebaseUrl.editor.mini.is-focused)
     -1:12.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.2.0 devunity:start (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "devunity": {
    "apikey": "anonymous"
  }
}
```
### Installed Packages

``` coffee
# User
altgr, v0.1.0
atom-beautify, v0.28.16
color-picker, v2.0.13
devunity, v2.2.0
minimap, v4.16.0
php-cs-fixer, v2.5.1
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by whmountains** [comment]
Happening to me too whenever I try to start a session.

**Comment by whmountains** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [devunity](https://github.com/aloncarmel/devunityatom) package, v2.2.0


### Stack Trace

Uncaught TypeError: atom.workspace.getActiveEditor is not a function

```
At /Users/mmc/.atom/packages/devunity/lib/devunity.coffee:410

TypeError: atom.workspace.getActiveEditor is not a function
    at DevunityView.getLanguage (/Users/mmc/.atom/packages/devunity/lib/devunity.coffee:410:29)
    at DevunityView.start (/Users/mmc/.atom/packages/devunity/lib/devunity.coffee:288:19)
    at atom-workspace.<anonymous> (/Users/mmc/.atom/packages/devunity/lib/devunity.coffee:217:63)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1133:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:354:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)
```

### Commands

```
     -1:39.7.0 application:new-file (atom-text-editor.editor.is-focused)
     -1:39.3.0 core:paste (atom-text-editor.editor.is-focused)
     -1:38.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -1:33.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:31.7.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -1:25.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:25 core:copy (atom-text-editor.editor.is-focused)
     -0:10.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:08.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:07.6.0 core:undo (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 devunity:start (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "file-type-icons",
      "linter-js-standard-engine",
      "linter-js-standard",
      "standard-formatter",
      "metrics",
      "linter",
      "color-picker",
      "nuclide"
    ],
    "projectHome": "/Users/mmc/code",
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "eclectic-syntax"
    ]
  },
  "devunity": {
    "apikey": "anonymous"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-modules, v1.6.7 (active)
autoprefixer, v3.3.0 (inactive)
color-picker, v2.2.2 (inactive)
cpack, v0.0.0 (inactive)
devunity, v2.2.0 (active)
eclectic-syntax, v0.2.1 (active)
file-icons, v1.7.23 (active)
focus-dark, v1.1.0 (inactive)
focus-light, v1.1.0 (inactive)
hyperclick, v0.0.39 (active)
js-hyperclick, v1.9.0 (active)
jumpy, v3.1.3 (inactive)
language-javascript-jsx, v0.3.7 (active)
less-than-slash, v0.16.0 (active)
linter, v1.11.18 (inactive)
linter-php, v1.3.1 (active)
markdown-writer, v2.6.1 (active)
merge-conflicts, v1.3.7 (inactive)
npm-install, v4.0.3 (inactive)
nuclide, v0.178.0 (inactive)
Zen, v0.16.4 (inactive)
zentabs, v0.8.7 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

Here's the dev report in case you can spot any pattern.

**Comment by cadenburleson** [comment]
I have this same problem.

**Comment by marcobonati** [comment]
Also for me the same problem.

**Comment by aloncarmel** [comment]
Thank you! fixed! please update !
