### ISSUE TITLE
Uncaught TypeError: this.buffer.on is not a function

### ISSUE THREAD

**Issue by Corxo** [aloncarmel/devunityatom#3]
[Enter steps to reproduce below:]
1. ..
2. ..

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [devunity](https://github.com/aloncarmel/devunityatom) package, v2.2.0
### Stack Trace

Uncaught TypeError: this.buffer.on is not a function

```
At C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:44

TypeError: this.buffer.on is not a function
    at new AtomAdapter (C:\Users\user\.atom\packages\devunity\lib\firepad-lib.js:2661:17)
    at new Firepad (C:\Users\user\.atom\packages\devunity\lib\firepad-lib.js:5083:29)
    at Function.Firepad (C:\Users\user\.atom\packages\devunity\lib\firepad-lib.js:5004:46)
    at file:///C:/Users/user/.atom/packages/devunity/lib/devunity.coffee:328:26
    at c (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:22:65)
    at C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:94:979
    at ac (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:44:20)
    at Td (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:94:965)
    at Rd.Eb (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:94:908)
    at Ud.Eb (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:95:417)
    at C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:110:406
    at C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:62:1194
    at Wb (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:58:222)
    at R (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:62:1171)
    at C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:110:386
    at Ra (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:29:154)
    at ue (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:110:358)
    at W (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:110:317)
    at Ae.h.cc (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:118:462)
    at md.h.bc (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:86:251)
    at ad.bc (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:77:364)
    at Q.Od (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:75:280)
    at Ec (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:61:234)
    at [object Object].W.onmessage (C:\Users\user\.atom\packages\devunity\node_modules\firebase\lib\firebase-node.js:60:111)
    at [object Object].EventTarget.dispatchEvent (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\lib\faye\websocket\api\event_target.js:22:30)
    at [object Object].instance._receiveMessage (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\lib\faye\websocket\api.js:142:10)
    at [object Object].<anonymous> (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\lib\faye\websocket\api.js:34:49)
    at emitOne (events.js:82:20)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\hybi.js:450:14)
    at pipe (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\node_modules\websocket-extensions\lib\pipeline\index.js:37:40)
    at [object Object].Pipeline._loop (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\node_modules\websocket-extensions\lib\pipeline\index.js:44:3)
    at [object Object].Pipeline.processIncomingMessage (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\node_modules\websocket-extensions\lib\pipeline\index.js:13:8)
    at [object Object].instance.processIncomingMessage (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\node_modules\websocket-extensions\lib\websocket_extensions.js:133:20)
    at [object Object].instance._emitMessage (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\hybi.js:441:22)
    at [object Object].instance._emitFrame (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\hybi.js:404:19)
    at [object Object].instance.parse (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\hybi.js:141:18)
    at [object Object].instance.parse (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\driver\client.js:62:58)
    at [object Object].IO.write (C:\Users\user\.atom\packages\devunity\node_modules\firebase\node_modules\faye-websocket\node_modules\websocket-driver\lib\websocket\streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
```
### Commands

```
     -0:03.0 devunity:start (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false
  },
  "devunity": {
    "apikey": "anonymous"
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.10
devunity, v2.2.0
linter, v1.11.3
minimap, v4.18.2
Remote-FTP, v0.7.15

# Dev
No dev packages
```

**Comment by aloncarmel** [comment]
Thank you! fixed! please update!
