### ISSUE TITLE
Failed to load the devunity package

### ISSUE THREAD

**Issue by Corxo** [aloncarmel/devunityatom#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [devunity](https://github.com/aloncarmel/devunityatom) package, v3.0.1
### Stack Trace

Failed to load the devunity package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/user/.atom/packages/devunity/lib/devunity.coffee:3:5)
    at Object.<anonymous> (file:///C:/Users/user/.atom/packages/devunity/lib/devunity.coffee:2:1)
    at Module._compile (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:663:34)
    at C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:115:28
    at Package.module.exports.Package.measure (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:390:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\atom-environment.js:682:21)
    at module.exports (C:\Users\user\AppData\Local\atom\app-1.3.2\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/user/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/user/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "devunity": {
    "apikey": ""
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.10
devunity, v3.0.1
linter, v1.11.3
minimap, v4.18.4
Remote-FTP, v0.7.15

# Dev
No dev packages
```

**Comment by aloncarmel** [comment]
Thanks for the report, im working on it.

**Comment by aloncarmel** [comment]
Thank you all. Fixed! please update!
