### ISSUE TITLE
Uncaught Error: sendOperation() called with invalid operation.

### ISSUE THREAD

**Issue by patrickshock** [aloncarmel/devunityatom#5]
This is my stack trace, I tried to type puts but i couldn't even type the p because it showed this error

Error: sendOperation() called with invalid operation.
    at assert (C:\Users\User\.atom\packages\devunity\lib\firepad-lib.js:1645:13)
    at FirebaseAdapter.firepad.FirebaseAdapter.FirebaseAdapter.sendOperation (C:\Users\User\.atom\packages\devunity\lib\firepad-lib.js:1403:5)
    at EditorClient.firepad.EditorClient.EditorClient.sendOperation (C:\Users\User\.atom\packages\devunity\lib\firepad-lib.js:2358:24)
    at Synchronized.firepad.Client.Synchronized.applyClient (C:\Users\User\.atom\packages\devunity\lib\firepad-lib.js:2066:12)
    at EditorClient.firepad.Client.Client.applyClient (C:\Users\User\.atom\packages\devunity\lib\firepad-lib.js:2021:30)
    at EditorClient.firepad.EditorClient.EditorClient.onChange (C:\Users\User\.atom\packages\devunity\lib\firepad-lib.js:2333:10)
    at AtomAdapter.change (C:\Users\User\.atom\packages\devunity\lib\firepad-lib.js:2265:52)
    at AtomAdapter.firepad.AtomAdapter.AtomAdapter.onChange (C:\Users\User\.atom\packages\devunity\lib\firepad-lib.js:2766:38)
    at C:\Users\User\.atom\packages\devunity\lib\firepad-lib.js:2645:59
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:727:20)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:712:19)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:915:16)
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:869:14)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\src\text-editor.js:1524:26)
    at C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\src\text-editor.js:1101:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\src\text-editor.js:2498:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\src\text-editor.js:2464:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\src\text-editor.js:1099:19)
    at TextEditor.module.exports.TextEditor.insertText (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\src\text-editor.js:1065:19)
    at TextEditor.object.(anonymous function) [as insertText] (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\src\text-editor-component.js:479:26)
    at HTMLDivElement.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.12.6\resources\app.asar\src\text-editor-component.js:3:59)

**Comment by aloncarmel** [comment]
Fixed! please update your package
