### ISSUE TITLE
Uncaught TypeError: _this.stopItem is not a function

### ISSUE THREAD

**Issue by aloncarmel** [aloncarmel/devunityatom#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [devunity](https://github.com/aloncarmel/devunityatom) package 4.0.0

### Stack Trace

Uncaught TypeError: _this.stopItem is not a function

```
At /Users/acarmel/.atom/packages/devunity/lib/devunity.coffee:560

TypeError: _this.stopItem is not a function
    at /packages/devunityatom/lib/devunity.coffee:560:12
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.didDestroyPaneItem (/app.asar/src/pane-container.js:304:27)
    at Pane.module.exports.Pane.removeItem (/app.asar/src/pane.js:597:16)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:658:16)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
     -1:18.9.0 devunity:start (span.syntax--text.syntax--plain.syntax--null-grammar)
     -0:25.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
devunity 4.0.0 
kite 0.20.1 
```

**Comment by aloncarmel** [comment]
Fixed in next version
